version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env/:/app/.env
    ports:
      - 3001:3001
    command: make run
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432